name: Qt QML CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: ${{ runner.tool_cache }}/Qt

    - name: Install Ninja
      run: choco install ninja

    - name: Configure PATH for Qt, MSVC, and Ninja
      shell: pwsh
      run: |
        echo "C:\\Qt\\5.15.2\\msvc2019_64\\bin" >> $Env:GITHUB_PATH
        echo "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat" >> $Env:GITHUB_PATH
        echo "C:\\Program Files\\Python312\\Lib\\site-packages\\ninja" >> $Env:GITHUB_PATH

    - name: Build project
      shell: pwsh
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_PREFIX_PATH="${{ runner.tool_cache }}\\Qt\\5.15.2\\msvc2019_64"
        ninja

    - name: Run application
      shell: pwsh
      run: |
        cd build
        .\path\to\your_executable.exe

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Build-Artifacts
        path: build/
