name: Qt QML CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: mirkancal/install-qt-action@v2
      with:
        version: '5.15.17'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: ${{ runner.tool_cache }}/Qt

    - name: Configure PATH
      run: |
        set PATH=${{ runner.tool_cache }}\Qt\5.15.2\msvc2019_64\bin;%PATH%

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH=${{ runner.tool_cache }}\Qt\5.15.17\msvc2019_64 ..
        nmake

    - name: Run application
      run: |
        cd build
        ./path/to/your_executable.exe

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Build-Artifacts
        path: build/

